# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itxpt_basic.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='itxpt_basic.proto',
  package='org.itxpt.ota',
  syntax='proto2',
  serialized_options=b'\302\363\030\0050.0.6',
  serialized_pb=b'\n\x11itxpt_basic.proto\x12\rorg.itxpt.ota\x1a google/protobuf/descriptor.proto\"\x89\x08\n\x06Header\x12\x10\n\x08priority\x18\x01 \x01(\x0c\x12\x12\n\nseq_number\x18\x02 \x01(\r\x12\x18\n\x10recorded_at_time\x18\x03 \x01(\x04\x12!\n\x19itxpt_basic_proto_version\x18\x04 \x01(\t\x1a\x93\x07\n\x12UserIdentification\x12\x61\n\x0fmodule_ref_type\x18\x01 \x01(\x0e\x32;.org.itxpt.ota.Header.UserIdentification.ModuleIdentityType:\x0bUid_UNKNOWN\x12\x0f\n\x07unit_id\x18\x02 \x01(\t\x12_\n\x10vehicle_ref_type\x18\n \x01(\x0e\x32<.org.itxpt.ota.Header.UserIdentification.VehicleIdentityType:\x07Vid_VIN\x12\x13\n\x0bvehicle_ref\x18\x0b \x01(\t\x12\x18\n\x10vehicle_ref_name\x18\x0c \x01(\t\x12\x61\n\x0f\x64river_ref_type\x18\x14 \x01(\x0e\x32;.org.itxpt.ota.Header.UserIdentification.DriverIdentityType:\x0b\x44id_UNKNOWN\x12\x12\n\ndriver_ref\x18\x15 \x01(\t\x12=\n\x0buser_ref_id\x18\x32 \x03(\x0b\x32(.org.itxpt.ota.Header.UserIdentification\x12\x16\n\x0e\x61\x63\x63ount_id_ref\x18< \x01(\t\"\x83\x01\n\x12ModuleIdentityType\x12\x0f\n\x0bUid_UNKNOWN\x10\x00\x12\x13\n\x0fUid_MAC_ADDRESS\x10\x01\x12\x11\n\rUid_SERIAL_NR\x10\x02\x12\x13\n\x0fUid_CERTIFICATE\x10\x03\x12\x10\n\x0cUid_HOSTNAME\x10\x04\x12\r\n\tUid_OTHER\x10\x05\"\x8f\x01\n\x13VehicleIdentityType\x12\x0b\n\x07Vid_VIN\x10\x00\x12\x13\n\x0fVid_VEHICLE_GID\x10\x01\x12\x1a\n\x16Vid_REGISTRATION_PLATE\x10\x02\x12\x16\n\x12Vid_VEHICLE_NUMBER\x10\x03\x12\x13\n\x0fVid_MAC_ADDRESS\x10\x04\x12\r\n\tVid_OTHER\x10\x05\"\x8a\x01\n\x12\x44riverIdentityType\x12\x0f\n\x0b\x44id_UNKNOWN\x10\x00\x12\x0b\n\x07\x44id_FMS\x10\x01\x12\x12\n\x0e\x44id_TACHOGRAPH\x10\x02\x12\x0c\n\x08\x44id_AVMS\x10\x03\x12\x11\n\rDid_TICKETING\x10\x04\x12\x12\n\x0e\x44id_BACKOFFICE\x10\x05\x12\r\n\tDid_OTHER\x10\x06*\x06\x08\xe8\x07\x10\xd0\x0f*\x06\x08\xe8\x07\x10\xd0\x0f:A\n\x19itxpt_basic_proto_version\x12\x1c.google.protobuf.FileOptions\x18\xb8\x8e\x03 \x01(\tB\t\xc2\xf3\x18\x05\x30.0.6'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


ITXPT_BASIC_PROTO_VERSION_FIELD_NUMBER = 51000
itxpt_basic_proto_version = _descriptor.FieldDescriptor(
  name='itxpt_basic_proto_version', full_name='org.itxpt.ota.itxpt_basic_proto_version', index=0,
  number=51000, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)

_HEADER_USERIDENTIFICATION_MODULEIDENTITYTYPE = _descriptor.EnumDescriptor(
  name='ModuleIdentityType',
  full_name='org.itxpt.ota.Header.UserIdentification.ModuleIdentityType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Uid_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Uid_MAC_ADDRESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Uid_SERIAL_NR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Uid_CERTIFICATE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Uid_HOSTNAME', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Uid_OTHER', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=670,
  serialized_end=801,
)
_sym_db.RegisterEnumDescriptor(_HEADER_USERIDENTIFICATION_MODULEIDENTITYTYPE)

_HEADER_USERIDENTIFICATION_VEHICLEIDENTITYTYPE = _descriptor.EnumDescriptor(
  name='VehicleIdentityType',
  full_name='org.itxpt.ota.Header.UserIdentification.VehicleIdentityType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Vid_VIN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Vid_VEHICLE_GID', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Vid_REGISTRATION_PLATE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Vid_VEHICLE_NUMBER', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Vid_MAC_ADDRESS', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Vid_OTHER', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=804,
  serialized_end=947,
)
_sym_db.RegisterEnumDescriptor(_HEADER_USERIDENTIFICATION_VEHICLEIDENTITYTYPE)

_HEADER_USERIDENTIFICATION_DRIVERIDENTITYTYPE = _descriptor.EnumDescriptor(
  name='DriverIdentityType',
  full_name='org.itxpt.ota.Header.UserIdentification.DriverIdentityType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Did_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Did_FMS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Did_TACHOGRAPH', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Did_AVMS', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Did_TICKETING', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Did_BACKOFFICE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Did_OTHER', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=950,
  serialized_end=1088,
)
_sym_db.RegisterEnumDescriptor(_HEADER_USERIDENTIFICATION_DRIVERIDENTITYTYPE)


_HEADER_USERIDENTIFICATION = _descriptor.Descriptor(
  name='UserIdentification',
  full_name='org.itxpt.ota.Header.UserIdentification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='module_ref_type', full_name='org.itxpt.ota.Header.UserIdentification.module_ref_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit_id', full_name='org.itxpt.ota.Header.UserIdentification.unit_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vehicle_ref_type', full_name='org.itxpt.ota.Header.UserIdentification.vehicle_ref_type', index=2,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vehicle_ref', full_name='org.itxpt.ota.Header.UserIdentification.vehicle_ref', index=3,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vehicle_ref_name', full_name='org.itxpt.ota.Header.UserIdentification.vehicle_ref_name', index=4,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='driver_ref_type', full_name='org.itxpt.ota.Header.UserIdentification.driver_ref_type', index=5,
      number=20, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='driver_ref', full_name='org.itxpt.ota.Header.UserIdentification.driver_ref', index=6,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_ref_id', full_name='org.itxpt.ota.Header.UserIdentification.user_ref_id', index=7,
      number=50, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_id_ref', full_name='org.itxpt.ota.Header.UserIdentification.account_id_ref', index=8,
      number=60, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HEADER_USERIDENTIFICATION_MODULEIDENTITYTYPE,
    _HEADER_USERIDENTIFICATION_VEHICLEIDENTITYTYPE,
    _HEADER_USERIDENTIFICATION_DRIVERIDENTITYTYPE,
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(1000, 2000), ],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=1096,
)

_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='org.itxpt.ota.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='priority', full_name='org.itxpt.ota.Header.priority', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq_number', full_name='org.itxpt.ota.Header.seq_number', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recorded_at_time', full_name='org.itxpt.ota.Header.recorded_at_time', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='itxpt_basic_proto_version', full_name='org.itxpt.ota.Header.itxpt_basic_proto_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_HEADER_USERIDENTIFICATION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(1000, 2000), ],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=1104,
)

_HEADER_USERIDENTIFICATION.fields_by_name['module_ref_type'].enum_type = _HEADER_USERIDENTIFICATION_MODULEIDENTITYTYPE
_HEADER_USERIDENTIFICATION.fields_by_name['vehicle_ref_type'].enum_type = _HEADER_USERIDENTIFICATION_VEHICLEIDENTITYTYPE
_HEADER_USERIDENTIFICATION.fields_by_name['driver_ref_type'].enum_type = _HEADER_USERIDENTIFICATION_DRIVERIDENTITYTYPE
_HEADER_USERIDENTIFICATION.fields_by_name['user_ref_id'].message_type = _HEADER_USERIDENTIFICATION
_HEADER_USERIDENTIFICATION.containing_type = _HEADER
_HEADER_USERIDENTIFICATION_MODULEIDENTITYTYPE.containing_type = _HEADER_USERIDENTIFICATION
_HEADER_USERIDENTIFICATION_VEHICLEIDENTITYTYPE.containing_type = _HEADER_USERIDENTIFICATION
_HEADER_USERIDENTIFICATION_DRIVERIDENTITYTYPE.containing_type = _HEADER_USERIDENTIFICATION
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.extensions_by_name['itxpt_basic_proto_version'] = itxpt_basic_proto_version
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {

  'UserIdentification' : _reflection.GeneratedProtocolMessageType('UserIdentification', (_message.Message,), {
    'DESCRIPTOR' : _HEADER_USERIDENTIFICATION,
    '__module__' : 'itxpt_basic_pb2'
    # @@protoc_insertion_point(class_scope:org.itxpt.ota.Header.UserIdentification)
    })
  ,
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'itxpt_basic_pb2'
  # @@protoc_insertion_point(class_scope:org.itxpt.ota.Header)
  })
_sym_db.RegisterMessage(Header)
_sym_db.RegisterMessage(Header.UserIdentification)

google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(itxpt_basic_proto_version)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
